//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_01._01_Gusakov323
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnfreezeRequest
    {
        public int UnfreezeRequestId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TargetBookId { get; set; }
        public string Status { get; set; }
        public string Reason { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> AdminId { get; set; }
        public Nullable<System.DateTime> ExecuteAt { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Users Users { get; set; }
    }
}
